[project]
name = "cardiee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.3.0",
    "pytest>=8.4.2",
    "typer>=0.17.3",
]
